project:
  type: book

book:
  title: "Quantum Technology"
  author: "Justin H. Wilson"
  date: "12/21/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - qubit.qmd
    - multiple_qubits.qmd
    - basic_algorithms.qmd
    - interlude.qmd
    - superconducting_qubits.qmd
    # - ion_trap_qubits.qmd
    # - photonic_qubits.qmd
    # - topological_qubits.qmd
    # - summary.qmd
    - references.qmd

bibliography: references.bib
# csl: https://www.zotero.org/styles/american-physics-society
csl: styles/american-physics-society.csl

filters:
  - tikz

crossref: 
  eq-prefix: Eq.
  fig-prefix: Fig.
  fig-title: Fig.

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    include-in-header:
      text: |
        <script>
        window.MathJax = {
          tex: {
            macros: {
              tr: "\\operatorname{tr}"
            }
          }
        };
        </script>
  # pdf:
  #   documentclass: scrreprt
  #   fontsize: 10pt
  #   pdf-engine: lualatex
  #   keep-tex: false
  #   pdf-engine-opts: 
  #     - --shell-escape
  #   include-in-header: 
  #     text: |
  #       \usepackage{braket}
  #       \DeclareMathOperator{\tr}{tr}

tikz:
  cache: true
  tex-dir: tikz-tex  # Optional: Specify directory to save .tex files
  format: svg

execute:
  freeze: auto
