project:
  type: book

book:
  title: "Quantum Technology"
  author: "Justin H. Wilson"
  date: "12/21/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - qubit.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib
csl: https://www.zotero.org/styles/american-physics-society

filters:
  - tikz

crossref: 
  eq-prefix: Eq.
  fig-prefix: Fig.
  fig-title: Fig.

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    include-in-header:
      text: |
        <script>
        window.MathJax = {
          tex: {
            macros: {
              tr: "\\operatorname{tr}"
            }
          }
        };
        </script>
  # pdf:
  #   documentclass: scrreprt
  #   pdf-engine: lualatex
  #   keep-tex: true
  #   pdf-engine-opts: 
  #     - --shell-escape
  #   include-in-header: 
  #     text: |
  #       \usepackage{tikz}
  #       \usepackage{braket}
  #       \DeclareMathOperator{\tr}{tr}
  #       \usetikzlibrary{quantikz2}
  #       \usetikzlibrary{arrows.meta}


tikz:
  cache: true
  tex-dir: tikz-tex  # Optional: Specify directory to save .tex files
  format: svg

execute:
  freeze: auto
